enum HTTP_STATUS {
  OK = 200,
  CREATED = 201,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500,
}

enum HTTP_ERROR_MESSAGE {
  NOT_FOUND = "Not found",
  INTERNAL_SERVER_ERROR = "Internal server error",
}

export { HTTP_STATUS, HTTP_ERROR_MESSAGE };
