enum HTTP_STATUS {
  CREATED = 201,
  INTERNAL_SERVER_ERROR = 500,
  NOT_FOUND = 404,
}

enum HTTP_ERROR_MESSAGE {
  INTERNAL_SERVER_ERROR = "Internal server error",
  NOT_FOUND = "Not found",
}

export { HTTP_STATUS, HTTP_ERROR_MESSAGE };
