enum HTTP_SUCCESS_STATUS {
  OK = 200,
  CREATED = 201,
}

enum HTTP_FAIL_STATUS {
  UNAUTHORIZED = 401,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500,
}

const HTTP_ERROR_MESSAGE = {
  [HTTP_FAIL_STATUS.UNAUTHORIZED]: "Unauthorized",
  [HTTP_FAIL_STATUS.NOT_FOUND]: "Not found",
  [HTTP_FAIL_STATUS.INTERNAL_SERVER_ERROR]: "Internal server error",
};

export { HTTP_SUCCESS_STATUS, HTTP_FAIL_STATUS, HTTP_ERROR_MESSAGE };
